#details/print function
print("Name:","Reethu")
print("Age:","28")
print("Qualification:","B-TECH")
print("Course:","Phython")
print("Address:","Thrissur")
print("name:","reethu")
input("Enter the name:")
int(input("Enter the age:"))
name = input("Enter the name:")
print(type(name))
age = int(input("Enter the age:"))
print(type(age))
print("------details/print function--------")